# -*- coding: utf-8 -*-
"""Assignment 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pvz0GfiHsgUYC3aRJ0En-HXcumASMOza

## Advanced Regular Expression Assignments

### Assignment 1: Extracting Phone Numbers

**Raw Text:**
Extract all valid Pakistani phone numbers from a given text.

**Example:**
"""

import re

text = "Please contact me at 0301-1234567 or 042-35678901 for further details."

phone_pattern = r'\b\d{4}-\d{7}\b|\b\d{3}-\d{8}\b'

phone_numbers = re.findall(phone_pattern,text)

print("Phone numbers Found:")

for number in phone_numbers:
  print(number)

"""### Assignment 2: Validating Email Addresses

**Raw Text:**
Validate email addresses according to Pakistani domain extensions (.pk).

**Example:**
```
Text: Contact us at info@example.com or support@domain.pk for assistance.
```
"""

text = "Contact us at info@example.com or support@domain.pk for assistance."

pattern = r'\b[A-z/d_%+-]+@[A-z/d.-]+\.[A-z\d]{2,}\b'

email_addresses = re.findall(pattern, text)

for email in email_addresses:
    print(email)

"""### Assignment 3: Extracting CNIC Numbers

**Raw Text:**
Extract all Pakistani CNIC (Computerized National Identity Card) numbers from a given text.

**Example:**
```
Text: My CNIC is 12345-6789012-3 and another one is 34567-8901234-5.

"""

text = "My CNIC is 12345-6789012-3 and another one is 34567-8901234-5"

cnic_pattern = r'\b\d{5}[/\\-]\d{7}[/\\-]\d{1}\b'

print("CNIC Numbers: ")

cnic_no = re.findall(cnic_pattern,text)

for cnic in cnic_no:
  print(cnic)

"""### Assignment 4: Identifying Urdu Words

**Raw Text:**
Identify and extract Urdu words from a mixed English-Urdu text.

**Example:**
```
Text: یہ sentence میں کچھ English words بھی ہیں۔
```

# In this example, the regular expression pattern r'[\u0600-\u06FF]+' is used to match one or more characters within the Unicode range of Arabic script, which includes Urdu alphabets. The re.findall() function then extracts all occurrences of this pattern from the input Urdu text.
"""

import re

text = "یہ sentence میں کچھ English words بھی ہیں۔"

urdu_pattern = r'[\u0600-\u06FF\s]+'

print("words in urdu ")

urdu_word = re.findall(urdu_pattern,text)

for word in urdu_word:
  print(word)

"""### Assignment 5: Finding Dates

**Raw Text:**
Find and extract dates in the format DD-MM-YYYY from a given text.

**Example:**
```
Text: The event will take place on 15-08-2023 and 23-09-2023.
```
"""

text = 'The event will take place on 15-08-2023 and 23-09-2023'

pattern = r'\d{2}[*-/\\]\d{2}[*-/\\]\d{2}'

print("Dates")

dates = re.findall(pattern,text)

for date in dates:
  print(dates)

"""### Assignment 6: Extracting URLs

**Raw Text:**
Extract all URLs from a text that belong to Pakistani domains.

**Example:**
```
Text: Visit http://www.example.pk or https://website.com.pk for more information.
"""

import re

text = "Visit http://www.example.pk or https://website.com.pk for more information https://websie.com.pk."

web_pattern = r'https?://[\w\d.-]+\.pk'

website = re.findall(web_pattern, text)


for web in website:
  print(web)

"""### Assignment 7: Analyzing Currency

**Raw Text:**
Extract and analyze currency amounts in Pakistani Rupees (PKR) from a given text.

**Example:**
```
Text: The product costs PKR 1500, while the deluxe version is priced at Rs. 2500.
```
"""

text = 'The product costs PKR 1500, while the deluxe version is priced at Rs. 2500'

pattern = r'PKR\s[0-9.+]{4}|Rs.\s[0-9.+]{4}'

currency = re.findall(pattern,text,)

print(currency)

import re

text = 'The product costs PKR 1500, while the deluxe version is priced at Rs. 2500'

pattern = r'PKR|Rs\. (\d+) + PKR|Rs\. (\d+)'

currency_matches = re.findall(pattern, text)


print(currency_matches)

"""### Assignment 8: Removing Punctuation

**Raw Text:**
Remove all punctuation marks from a text while preserving Urdu characters.

**Example:**
```
Text: کیا! آپ, یہاں؟
```

"""

import re

text = 'کیا! آپ, یہاں؟'

# Remove punctuation using regular expression
cleaned_text = re.sub(r'[^\w\s]','' ,text)

print(cleaned_text)

"""### Assignment 9: Extracting City Names

**Raw Text:**
Extract names of Pakistani cities from a given text.

**Example:**
```
Text: Lahore, Karachi, Islamabad, and Peshawar are major cities of Pakistan.

"""

text = "Lahore, Karachi, Islamabad, and Peshawar are major cities of Pakistan."

pattern =r'\b[A-Z][a-z]+\b(?:!\bPakistan\b)'

city_name = re.findall(pattern, text)

for city in city_names:
  print(city)

"""### Assignment 10: Analyzing Vehicle Numbers

**Raw Text:**
Identify and extract Pakistani vehicle registration numbers (e.g., ABC-123) from a text.

**Example:**
```
Text: I saw a car with the number plate LEA-567 near the market.
```

"""

text = "I saw a car with the number plate LEA-567 near the market."

pattern = r'\b[A-z]{3}-\d{3}\b'

vehicle_registeratoin_no = re.findall(pattern, text)

print(vehicle_registeratoin_no)